/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2026-07-10 06:43:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.owner;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class contract_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/owner/sidebar.jsp", Long.valueOf(1783665486351L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"zh-CN\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>合同管理 - 房屋租赁系统</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/style.css\">\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            display: flex;\n");
      out.write("            min-height: 100vh;\n");
      out.write("            background-color: #f0f2f5;\n");
      out.write("            font-family: \"Microsoft YaHei\", sans-serif;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .main-content {\n");
      out.write("            flex: 1;\n");
      out.write("            padding: 24px;\n");
      out.write("            margin-left: 220px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .page-header {\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            align-items: center;\n");
      out.write("            margin-bottom: 24px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .page-header h1 {\n");
      out.write("            font-size: 24px;\n");
      out.write("            color: #333;\n");
      out.write("            margin: 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .search-bar {\n");
      out.write("            background: #fff;\n");
      out.write("            padding: 16px;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.06);\n");
      out.write("            margin-bottom: 16px;\n");
      out.write("            display: flex;\n");
      out.write("            gap: 12px;\n");
      out.write("            align-items: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .search-bar select {\n");
      out.write("            padding: 8px 12px;\n");
      out.write("            border: 1px solid #d9d9d9;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            font-size: 14px;\n");
      out.write("            outline: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .search-bar select:focus {\n");
      out.write("            border-color: #1890ff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn {\n");
      out.write("            padding: 8px 16px;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            font-size: 14px;\n");
      out.write("            transition: all 0.2s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary {\n");
      out.write("            background: #1890ff;\n");
      out.write("            color: #fff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary:hover {\n");
      out.write("            background: #40a9ff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-danger {\n");
      out.write("            background: #ff4d4f;\n");
      out.write("            color: #fff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-danger:hover {\n");
      out.write("            background: #ff7875;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-warning {\n");
      out.write("            background: #faad14;\n");
      out.write("            color: #fff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-warning:hover {\n");
      out.write("            background: #ffc53d;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-link {\n");
      out.write("            background: none;\n");
      out.write("            border: none;\n");
      out.write("            color: #1890ff;\n");
      out.write("            cursor: pointer;\n");
      out.write("            padding: 4px 8px;\n");
      out.write("            font-size: 13px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-link:hover {\n");
      out.write("            color: #40a9ff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-link.danger {\n");
      out.write("            color: #ff4d4f;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-link.danger:hover {\n");
      out.write("            color: #ff7875;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .data-table-wrapper {\n");
      out.write("            background: #fff;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.06);\n");
      out.write("            overflow: hidden;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .data-table {\n");
      out.write("            width: 100%;\n");
      out.write("            border-collapse: collapse;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .data-table th {\n");
      out.write("            background: #fafafa;\n");
      out.write("            padding: 12px 16px;\n");
      out.write("            text-align: left;\n");
      out.write("            font-weight: 600;\n");
      out.write("            color: #333;\n");
      out.write("            border-bottom: 1px solid #f0f0f0;\n");
      out.write("            font-size: 14px;\n");
      out.write("            white-space: nowrap;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .data-table td {\n");
      out.write("            padding: 12px 16px;\n");
      out.write("            border-bottom: 1px solid #f0f0f0;\n");
      out.write("            color: #666;\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .data-table tr:hover {\n");
      out.write("            background: #f5f5f5;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-tag {\n");
      out.write("            display: inline-block;\n");
      out.write("            padding: 2px 8px;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            font-size: 12px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-active {\n");
      out.write("            background: #f6ffed;\n");
      out.write("            color: #52c41a;\n");
      out.write("            border: 1px solid #b7eb8f;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-expired {\n");
      out.write("            background: #f5f5f5;\n");
      out.write("            color: #999;\n");
      out.write("            border: 1px solid #d9d9d9;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-terminated {\n");
      out.write("            background: #fff1f0;\n");
      out.write("            color: #ff4d4f;\n");
      out.write("            border: 1px solid #ffa39e;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-pending {\n");
      out.write("            background: #fff7e6;\n");
      out.write("            color: #fa8c16;\n");
      out.write("            border: 1px solid #ffd591;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .pagination {\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: flex-end;\n");
      out.write("            align-items: center;\n");
      out.write("            padding: 16px;\n");
      out.write("            gap: 8px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .pagination button {\n");
      out.write("            padding: 6px 12px;\n");
      out.write("            border: 1px solid #d9d9d9;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            background: #fff;\n");
      out.write("            cursor: pointer;\n");
      out.write("            font-size: 14px;\n");
      out.write("            color: #333;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .pagination button:hover:not(:disabled) {\n");
      out.write("            border-color: #1890ff;\n");
      out.write("            color: #1890ff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .pagination button:disabled {\n");
      out.write("            cursor: not-allowed;\n");
      out.write("            color: #d9d9d9;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .pagination button.active {\n");
      out.write("            background: #1890ff;\n");
      out.write("            color: #fff;\n");
      out.write("            border-color: #1890ff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .pagination .page-info {\n");
      out.write("            font-size: 14px;\n");
      out.write("            color: #666;\n");
      out.write("            margin: 0 8px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* 模态框样式 */\n");
      out.write("        .modal-overlay {\n");
      out.write("            display: none;\n");
      out.write("            position: fixed;\n");
      out.write("            top: 0;\n");
      out.write("            left: 0;\n");
      out.write("            right: 0;\n");
      out.write("            bottom: 0;\n");
      out.write("            background: rgba(0, 0, 0, 0.5);\n");
      out.write("            z-index: 1000;\n");
      out.write("            justify-content: center;\n");
      out.write("            align-items: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .modal-overlay.active {\n");
      out.write("            display: flex;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .modal {\n");
      out.write("            background: #fff;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            width: 560px;\n");
      out.write("            max-width: 90vw;\n");
      out.write("            max-height: 85vh;\n");
      out.write("            overflow-y: auto;\n");
      out.write("            box-shadow: 0 8px 32px rgba(0, 0, 0, 0.15);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .modal-header {\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            align-items: center;\n");
      out.write("            padding: 16px 24px;\n");
      out.write("            border-bottom: 1px solid #f0f0f0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .modal-header h3 {\n");
      out.write("            margin: 0;\n");
      out.write("            font-size: 18px;\n");
      out.write("            color: #333;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .modal-close {\n");
      out.write("            background: none;\n");
      out.write("            border: none;\n");
      out.write("            font-size: 20px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            color: #999;\n");
      out.write("            padding: 0 4px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .modal-close:hover {\n");
      out.write("            color: #333;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .modal-body {\n");
      out.write("            padding: 24px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group {\n");
      out.write("            margin-bottom: 16px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group label {\n");
      out.write("            display: block;\n");
      out.write("            margin-bottom: 6px;\n");
      out.write("            font-size: 14px;\n");
      out.write("            color: #333;\n");
      out.write("            font-weight: 500;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group label .required {\n");
      out.write("            color: #ff4d4f;\n");
      out.write("            margin-left: 2px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group input,\n");
      out.write("        .form-group select {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 8px 12px;\n");
      out.write("            border: 1px solid #d9d9d9;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            font-size: 14px;\n");
      out.write("            outline: none;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group input:focus,\n");
      out.write("        .form-group select:focus {\n");
      out.write("            border-color: #1890ff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-row {\n");
      out.write("            display: flex;\n");
      out.write("            gap: 16px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-row .form-group {\n");
      out.write("            flex: 1;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .modal-footer {\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: flex-end;\n");
      out.write("            gap: 12px;\n");
      out.write("            padding: 16px 24px;\n");
      out.write("            border-top: 1px solid #f0f0f0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .empty-tip {\n");
      out.write("            text-align: center;\n");
      out.write("            padding: 48px;\n");
      out.write("            color: #999;\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .action-btns {\n");
      out.write("            white-space: nowrap;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    ");
      out.write("\n");
      out.write("<div class=\"sidebar\">\n");
      out.write("    <div class=\"sidebar-logo\">房屋租赁系统</div>\n");
      out.write("    <ul class=\"sidebar-menu\">\n");
      out.write("        <li><a href=\"dashboard.jsp\"><span class=\"icon\">&#127968;</span>概览</a></li>\n");
      out.write("        <li><a href=\"house.jsp\"><span class=\"icon\">&#127970;</span>房源管理</a></li>\n");
      out.write("        <li><a href=\"contract.jsp\"><span class=\"icon\">&#128196;</span>合同管理</a></li>\n");
      out.write("        <li><a href=\"payment.jsp\"><span class=\"icon\">&#128176;</span>费用管理</a></li>\n");
      out.write("        <li><a href=\"profile.jsp\"><span class=\"icon\">&#128100;</span>个人信息</a></li>\n");
      out.write("        <li><a href=\"javascript:void(0)\" onclick=\"logout()\"><span class=\"icon\">&#128682;</span>退出登录</a></li>\n");
      out.write("    </ul>\n");
      out.write("</div>\n");
      out.write("<script>\n");
      out.write("    function logout() {\n");
      out.write("        localStorage.removeItem('token');\n");
      out.write("        localStorage.removeItem('user');\n");
      out.write("        localStorage.removeItem('role');\n");
      out.write("        window.location.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login.jsp';\n");
      out.write("    }\n");
      out.write("    // 高亮当前菜单\n");
      out.write("    document.addEventListener('DOMContentLoaded', function() {\n");
      out.write("        var currentPage = window.location.pathname.split('/').pop();\n");
      out.write("        var items = document.querySelectorAll('.sidebar-menu li a');\n");
      out.write("        items.forEach(function(item) {\n");
      out.write("            if (item.getAttribute('href') === currentPage) {\n");
      out.write("                item.parentElement.classList.add('active');\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"main-content\">\n");
      out.write("        <div class=\"page-header\">\n");
      out.write("            <h1>合同管理</h1>\n");
      out.write("            <button class=\"btn btn-primary\" onclick=\"openAddModal()\">+ 创建合同</button>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"search-bar\">\n");
      out.write("            <select id=\"statusFilter\" onchange=\"loadContracts()\">\n");
      out.write("                <option value=\"\">全部状态</option>\n");
      out.write("                <option value=\"pending\">待生效</option>\n");
      out.write("                <option value=\"active\">生效中</option>\n");
      out.write("                <option value=\"expired\">已到期</option>\n");
      out.write("                <option value=\"terminated\">已终止</option>\n");
      out.write("            </select>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"data-table-wrapper\">\n");
      out.write("            <table class=\"data-table\">\n");
      out.write("                <thead>\n");
      out.write("                    <tr>\n");
      out.write("                        <th>编号</th>\n");
      out.write("                        <th>房源地址</th>\n");
      out.write("                        <th>租户</th>\n");
      out.write("                        <th>签订日期</th>\n");
      out.write("                        <th>起始日期</th>\n");
      out.write("                        <th>终止日期</th>\n");
      out.write("                        <th>月租金(元)</th>\n");
      out.write("                        <th>押金(元)</th>\n");
      out.write("                        <th>状态</th>\n");
      out.write("                        <th>操作</th>\n");
      out.write("                    </tr>\n");
      out.write("                </thead>\n");
      out.write("                <tbody id=\"contractTableBody\">\n");
      out.write("                    <tr><td colspan=\"10\" class=\"empty-tip\">加载中...</td></tr>\n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("            <div class=\"pagination\" id=\"pagination\"></div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- 创建合同模态框 -->\n");
      out.write("    <div class=\"modal-overlay\" id=\"contractModal\">\n");
      out.write("        <div class=\"modal\">\n");
      out.write("            <div class=\"modal-header\">\n");
      out.write("                <h3>创建合同</h3>\n");
      out.write("                <button class=\"modal-close\" onclick=\"closeModal()\">&times;</button>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-body\">\n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label>房源 <span class=\"required\">*</span></label>\n");
      out.write("                        <select id=\"houseId\">\n");
      out.write("                            <option value=\"\">请选择房源</option>\n");
      out.write("                        </select>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label>租户ID <span class=\"required\">*</span></label>\n");
      out.write("                        <input type=\"number\" id=\"tenantId\" placeholder=\"请输入租户ID\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label>签订日期 <span class=\"required\">*</span></label>\n");
      out.write("                    <input type=\"date\" id=\"signDate\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label>起始日期 <span class=\"required\">*</span></label>\n");
      out.write("                        <input type=\"date\" id=\"startDate\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label>终止日期 <span class=\"required\">*</span></label>\n");
      out.write("                        <input type=\"date\" id=\"endDate\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label>月租金(元) <span class=\"required\">*</span></label>\n");
      out.write("                        <input type=\"number\" id=\"monthlyRent\" placeholder=\"请输入月租金\" step=\"0.01\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label>押金(元) <span class=\"required\">*</span></label>\n");
      out.write("                        <input type=\"number\" id=\"deposit\" placeholder=\"请输入押金\" step=\"0.01\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-footer\">\n");
      out.write("                <button class=\"btn\" onclick=\"closeModal()\">取消</button>\n");
      out.write("                <button class=\"btn btn-primary\" onclick=\"saveContract()\">创建</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/common.js\"></script>\n");
      out.write("    <script>\n");
      out.write("        var currentPage = 1;\n");
      out.write("        var pageSize = 10;\n");
      out.write("\n");
      out.write("        /**\n");
      out.write("         * 页面初始化\n");
      out.write("         */\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\n");
      out.write("            loadContracts();\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        /**\n");
      out.write("         * 加载合同列表\n");
      out.write("         */\n");
      out.write("        function loadContracts() {\n");
      out.write("            var status = document.getElementById('statusFilter').value;\n");
      out.write("            var token = localStorage.getItem('token');\n");
      out.write("\n");
      out.write("            var url = getContextPath() + '/api/owner/contract?page=' + currentPage + '&pageSize=' + pageSize;\n");
      out.write("            if (status) url += '&status=' + status;\n");
      out.write("\n");
      out.write("            fetch(url, {\n");
      out.write("                method: 'GET',\n");
      out.write("                headers: { 'Authorization': 'Bearer ' + token }\n");
      out.write("            })\n");
      out.write("            .then(function(response) { return response.json(); })\n");
      out.write("            .then(function(result) {\n");
      out.write("                if (result.code === 200 && result.data) {\n");
      out.write("                    renderTable(result.data.list || []);\n");
      out.write("                    renderPagination(result.data.total || 0);\n");
      out.write("                } else {\n");
      out.write("                    alert('获取合同列表失败：' + (result.message || '未知错误'));\n");
      out.write("                }\n");
      out.write("            })\n");
      out.write("            .catch(function(error) {\n");
      out.write("                console.error('加载合同列表失败：', error);\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /**\n");
      out.write("         * 渲染合同表格\n");
      out.write("         */\n");
      out.write("        function renderTable(list) {\n");
      out.write("            var tbody = document.getElementById('contractTableBody');\n");
      out.write("            if (list.length === 0) {\n");
      out.write("                tbody.innerHTML = '<tr><td colspan=\"10\" class=\"empty-tip\">暂无数据</td></tr>';\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            var html = '';\n");
      out.write("            list.forEach(function(item) {\n");
      out.write("                var statusClass = '';\n");
      out.write("                var statusText = '';\n");
      out.write("                if (item.status === 'active') { statusClass = 'status-active'; statusText = '生效中'; }\n");
      out.write("                else if (item.status === 'expired') { statusClass = 'status-expired'; statusText = '已到期'; }\n");
      out.write("                else if (item.status === 'terminated') { statusClass = 'status-terminated'; statusText = '已终止'; }\n");
      out.write("                else { statusClass = 'status-pending'; statusText = '待生效'; }\n");
      out.write("\n");
      out.write("                html += '<tr>';\n");
      out.write("                html += '<td>' + item.id + '</td>';\n");
      out.write("                html += '<td>' + escapeHtml(item.houseAddress || '--') + '</td>';\n");
      out.write("                html += '<td>' + escapeHtml(item.tenantName || '--') + '</td>';\n");
      out.write("                html += '<td>' + (item.signDate || '--') + '</td>';\n");
      out.write("                html += '<td>' + (item.startDate || '--') + '</td>';\n");
      out.write("                html += '<td>' + (item.endDate || '--') + '</td>';\n");
      out.write("                html += '<td>' + item.monthlyRent + '</td>';\n");
      out.write("                html += '<td>' + item.deposit + '</td>';\n");
      out.write("                html += '<td><span class=\"status-tag ' + statusClass + '\">' + statusText + '</span></td>';\n");
      out.write("                html += '<td class=\"action-btns\">';\n");
      out.write("                if (item.status === 'active') {\n");
      out.write("                    html += '<button class=\"btn-link danger\" onclick=\"terminateContract(' + item.id + ')\">终止</button>';\n");
      out.write("                }\n");
      out.write("                if (item.status === 'active' || item.status === 'pending') {\n");
      out.write("                    html += '<button class=\"btn-link\" onclick=\"expireContract(' + item.id + ')\">到期</button>';\n");
      out.write("                }\n");
      out.write("                html += '</td>';\n");
      out.write("                html += '</tr>';\n");
      out.write("            });\n");
      out.write("            tbody.innerHTML = html;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /**\n");
      out.write("         * 渲染分页\n");
      out.write("         */\n");
      out.write("        function renderPagination(total) {\n");
      out.write("            var container = document.getElementById('pagination');\n");
      out.write("            var totalPages = Math.ceil(total / pageSize);\n");
      out.write("            if (totalPages <= 1) {\n");
      out.write("                container.innerHTML = '<span class=\"page-info\">共 ' + total + ' 条记录</span>';\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            var html = '<button onclick=\"goPage(' + (currentPage - 1) + ')\" ' + (currentPage <= 1 ? 'disabled' : '') + '>上一页</button>';\n");
      out.write("            for (var i = 1; i <= totalPages; i++) {\n");
      out.write("                html += '<button class=\"' + (i === currentPage ? 'active' : '') + '\" onclick=\"goPage(' + i + ')\">' + i + '</button>';\n");
      out.write("            }\n");
      out.write("            html += '<button onclick=\"goPage(' + (currentPage + 1) + ')\" ' + (currentPage >= totalPages ? 'disabled' : '') + '>下一页</button>';\n");
      out.write("            html += '<span class=\"page-info\">共 ' + total + ' 条记录</span>';\n");
      out.write("            container.innerHTML = html;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /**\n");
      out.write("         * 翻页\n");
      out.write("         */\n");
      out.write("        function goPage(page) {\n");
      out.write("            currentPage = page;\n");
      out.write("            loadContracts();\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /**\n");
      out.write("         * 打开创建合同模态框\n");
      out.write("         */\n");
      out.write("        function openAddModal() {\n");
      out.write("            document.getElementById('tenantId').value = '';\n");
      out.write("            document.getElementById('signDate').value = '';\n");
      out.write("            document.getElementById('startDate').value = '';\n");
      out.write("            document.getElementById('endDate').value = '';\n");
      out.write("            document.getElementById('monthlyRent').value = '';\n");
      out.write("            document.getElementById('deposit').value = '';\n");
      out.write("\n");
      out.write("            // 加载空闲房源列表\n");
      out.write("            loadFreeHouses();\n");
      out.write("            document.getElementById('contractModal').classList.add('active');\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /**\n");
      out.write("         * 加载空闲房源下拉列表\n");
      out.write("         */\n");
      out.write("        function loadFreeHouses() {\n");
      out.write("            var token = localStorage.getItem('token');\n");
      out.write("            fetch(getContextPath() + '/api/owner/house?page=1&pageSize=100&status=free', {\n");
      out.write("                method: 'GET',\n");
      out.write("                headers: { 'Authorization': 'Bearer ' + token }\n");
      out.write("            })\n");
      out.write("            .then(function(response) { return response.json(); })\n");
      out.write("            .then(function(result) {\n");
      out.write("                var select = document.getElementById('houseId');\n");
      out.write("                select.innerHTML = '<option value=\"\">请选择房源</option>';\n");
      out.write("                if (result.code === 200 && result.data && result.data.list) {\n");
      out.write("                    result.data.list.forEach(function(house) {\n");
      out.write("                        select.innerHTML += '<option value=\"' + house.id + '\" data-rent=\"' + house.rentPrice + '\">' + escapeHtml(house.address) + '</option>';\n");
      out.write("                    });\n");
      out.write("                }\n");
      out.write("            })\n");
      out.write("            .catch(function(error) {\n");
      out.write("                console.error('加载房源列表失败：', error);\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /**\n");
      out.write("         * 关闭模态框\n");
      out.write("         */\n");
      out.write("        function closeModal() {\n");
      out.write("            document.getElementById('contractModal').classList.remove('active');\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /**\n");
      out.write("         * 保存合同\n");
      out.write("         */\n");
      out.write("        function saveContract() {\n");
      out.write("            var houseId = document.getElementById('houseId').value;\n");
      out.write("            var tenantId = document.getElementById('tenantId').value;\n");
      out.write("            var signDate = document.getElementById('signDate').value;\n");
      out.write("            var startDate = document.getElementById('startDate').value;\n");
      out.write("            var endDate = document.getElementById('endDate').value;\n");
      out.write("            var monthlyRent = document.getElementById('monthlyRent').value;\n");
      out.write("            var deposit = document.getElementById('deposit').value;\n");
      out.write("\n");
      out.write("            if (!houseId) { alert('请选择房源'); return; }\n");
      out.write("            if (!tenantId) { alert('请输入租户ID'); return; }\n");
      out.write("            if (!signDate) { alert('请选择签订日期'); return; }\n");
      out.write("            if (!startDate) { alert('请选择起始日期'); return; }\n");
      out.write("            if (!endDate) { alert('请选择终止日期'); return; }\n");
      out.write("            if (!monthlyRent || monthlyRent <= 0) { alert('请输入有效月租金'); return; }\n");
      out.write("            if (!deposit || deposit < 0) { alert('请输入有效押金'); return; }\n");
      out.write("\n");
      out.write("            var data = {\n");
      out.write("                houseId: parseInt(houseId),\n");
      out.write("                tenantId: parseInt(tenantId),\n");
      out.write("                signDate: signDate,\n");
      out.write("                startDate: startDate,\n");
      out.write("                endDate: endDate,\n");
      out.write("                monthlyRent: parseFloat(monthlyRent),\n");
      out.write("                deposit: parseFloat(deposit)\n");
      out.write("            };\n");
      out.write("\n");
      out.write("            var token = localStorage.getItem('token');\n");
      out.write("            fetch(getContextPath() + '/api/owner/contract', {\n");
      out.write("                method: 'POST',\n");
      out.write("                headers: {\n");
      out.write("                    'Content-Type': 'application/json',\n");
      out.write("                    'Authorization': 'Bearer ' + token\n");
      out.write("                },\n");
      out.write("                body: JSON.stringify(data)\n");
      out.write("            })\n");
      out.write("            .then(function(response) { return response.json(); })\n");
      out.write("            .then(function(result) {\n");
      out.write("                if (result.code === 200) {\n");
      out.write("                    alert('合同创建成功');\n");
      out.write("                    closeModal();\n");
      out.write("                    loadContracts();\n");
      out.write("                } else {\n");
      out.write("                    alert('操作失败：' + (result.message || '未知错误'));\n");
      out.write("                }\n");
      out.write("            })\n");
      out.write("            .catch(function(error) {\n");
      out.write("                console.error('创建合同失败：', error);\n");
      out.write("                alert('操作失败，请稍后重试');\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /**\n");
      out.write("         * 终止合同\n");
      out.write("         */\n");
      out.write("        function terminateContract(id) {\n");
      out.write("            if (!confirm('确定要终止该合同吗？终止后不可恢复。')) return;\n");
      out.write("\n");
      out.write("            var token = localStorage.getItem('token');\n");
      out.write("            fetch(getContextPath() + '/api/owner/contract?action=terminate&id=' + id, {\n");
      out.write("                method: 'PUT',\n");
      out.write("                headers: { 'Authorization': 'Bearer ' + token }\n");
      out.write("            })\n");
      out.write("            .then(function(response) { return response.json(); })\n");
      out.write("            .then(function(result) {\n");
      out.write("                if (result.code === 200) {\n");
      out.write("                    alert('合同已终止');\n");
      out.write("                    loadContracts();\n");
      out.write("                } else {\n");
      out.write("                    alert('操作失败：' + (result.message || '未知错误'));\n");
      out.write("                }\n");
      out.write("            })\n");
      out.write("            .catch(function(error) {\n");
      out.write("                console.error('终止合同失败：', error);\n");
      out.write("                alert('操作失败，请稍后重试');\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /**\n");
      out.write("         * 标记合同到期\n");
      out.write("         */\n");
      out.write("        function expireContract(id) {\n");
      out.write("            if (!confirm('确定要将该合同标记为到期吗？')) return;\n");
      out.write("\n");
      out.write("            var token = localStorage.getItem('token');\n");
      out.write("            fetch(getContextPath() + '/api/owner/contract?action=expire&id=' + id, {\n");
      out.write("                method: 'PUT',\n");
      out.write("                headers: { 'Authorization': 'Bearer ' + token }\n");
      out.write("            })\n");
      out.write("            .then(function(response) { return response.json(); })\n");
      out.write("            .then(function(result) {\n");
      out.write("                if (result.code === 200) {\n");
      out.write("                    alert('合同已标记为到期');\n");
      out.write("                    loadContracts();\n");
      out.write("                } else {\n");
      out.write("                    alert('操作失败：' + (result.message || '未知错误'));\n");
      out.write("                }\n");
      out.write("            })\n");
      out.write("            .catch(function(error) {\n");
      out.write("                console.error('到期操作失败：', error);\n");
      out.write("                alert('操作失败，请稍后重试');\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /**\n");
      out.write("         * HTML转义\n");
      out.write("         */\n");
      out.write("        function escapeHtml(text) {\n");
      out.write("            if (!text) return '';\n");
      out.write("            var div = document.createElement('div');\n");
      out.write("            div.appendChild(document.createTextNode(text));\n");
      out.write("            return div.innerHTML;\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
