/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2026-07-10 07:01:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.owner;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/owner/sidebar.jsp", Long.valueOf(1783666824373L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"zh-CN\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>房东概览 - 房屋租赁系统</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/style.css\">\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            display: flex;\n");
      out.write("            min-height: 100vh;\n");
      out.write("            background-color: #f0f2f5;\n");
      out.write("            font-family: \"Microsoft YaHei\", sans-serif;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .main-content {\n");
      out.write("            flex: 1;\n");
      out.write("            padding: 24px;\n");
      out.write("            margin-left: 220px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .page-header {\n");
      out.write("            margin-bottom: 24px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .page-header h1 {\n");
      out.write("            font-size: 24px;\n");
      out.write("            color: #333;\n");
      out.write("            margin: 0 0 8px 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .page-header p {\n");
      out.write("            color: #666;\n");
      out.write("            margin: 0;\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .stats-grid {\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: repeat(auto-fill, minmax(220px, 1fr));\n");
      out.write("            gap: 20px;\n");
      out.write("            margin-bottom: 24px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .stat-card {\n");
      out.write("            background: #fff;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            padding: 24px;\n");
      out.write("            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.06);\n");
      out.write("            transition: transform 0.2s, box-shadow 0.2s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .stat-card:hover {\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("            box-shadow: 0 4px 16px rgba(0, 0, 0, 0.1);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .stat-card .stat-icon {\n");
      out.write("            width: 48px;\n");
      out.write("            height: 48px;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            font-size: 24px;\n");
      out.write("            margin-bottom: 16px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .stat-card .stat-value {\n");
      out.write("            font-size: 32px;\n");
      out.write("            font-weight: bold;\n");
      out.write("            color: #333;\n");
      out.write("            margin-bottom: 4px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .stat-card .stat-label {\n");
      out.write("            font-size: 14px;\n");
      out.write("            color: #999;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .stat-card:nth-child(1) .stat-icon { background: #e6f7ff; color: #1890ff; }\n");
      out.write("        .stat-card:nth-child(2) .stat-icon { background: #f6ffed; color: #52c41a; }\n");
      out.write("        .stat-card:nth-child(3) .stat-icon { background: #fff7e6; color: #fa8c16; }\n");
      out.write("        .stat-card:nth-child(4) .stat-icon { background: #f9f0ff; color: #722ed1; }\n");
      out.write("        .stat-card:nth-child(5) .stat-icon { background: #fff1f0; color: #f5222d; }\n");
      out.write("\n");
      out.write("        .welcome-section {\n");
      out.write("            background: linear-gradient(135deg, #1890ff, #722ed1);\n");
      out.write("            border-radius: 8px;\n");
      out.write("            padding: 32px;\n");
      out.write("            color: #fff;\n");
      out.write("            margin-bottom: 24px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .welcome-section h2 {\n");
      out.write("            margin: 0 0 8px 0;\n");
      out.write("            font-size: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .welcome-section p {\n");
      out.write("            margin: 0;\n");
      out.write("            opacity: 0.85;\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    ");
      out.write("\n");
      out.write("<div class=\"sidebar\">\n");
      out.write("    <div class=\"sidebar-logo\">房屋租赁系统</div>\n");
      out.write("    <ul class=\"sidebar-menu\">\n");
      out.write("        <li><a href=\"dashboard.jsp\"><span class=\"icon\">&#127968;</span>概览</a></li>\n");
      out.write("        <li><a href=\"house.jsp\"><span class=\"icon\">&#127970;</span>房源管理</a></li>\n");
      out.write("        <li><a href=\"contract.jsp\"><span class=\"icon\">&#128196;</span>合同管理</a></li>\n");
      out.write("        <li><a href=\"payment.jsp\"><span class=\"icon\">&#128176;</span>费用管理</a></li>\n");
      out.write("        <li><a href=\"profile.jsp\"><span class=\"icon\">&#128100;</span>个人信息</a></li>\n");
      out.write("        <li><a href=\"javascript:void(0)\" onclick=\"logout()\"><span class=\"icon\">&#128682;</span>退出登录</a></li>\n");
      out.write("    </ul>\n");
      out.write("</div>\n");
      out.write("<script>\n");
      out.write("    function logout() {\n");
      out.write("        localStorage.removeItem('token');\n");
      out.write("        localStorage.removeItem('user');\n");
      out.write("        localStorage.removeItem('role');\n");
      out.write("        window.location.href = '/login.jsp';\n");
      out.write("    }\n");
      out.write("    // 高亮当前菜单\n");
      out.write("    document.addEventListener('DOMContentLoaded', function() {\n");
      out.write("        var currentPage = window.location.pathname.split('/').pop();\n");
      out.write("        var items = document.querySelectorAll('.sidebar-menu li a');\n");
      out.write("        items.forEach(function(item) {\n");
      out.write("            if (item.getAttribute('href') === currentPage) {\n");
      out.write("                item.parentElement.classList.add('active');\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"main-content\">\n");
      out.write("        <div class=\"welcome-section\">\n");
      out.write("            <h2 id=\"welcomeText\">欢迎回来！</h2>\n");
      out.write("            <p>这是您的房东控制台，可以在这里管理房源、合同和费用信息。</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"page-header\">\n");
      out.write("            <h1>数据概览</h1>\n");
      out.write("            <p>查看您的房源和业务概况</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"stats-grid\">\n");
      out.write("            <div class=\"stat-card\">\n");
      out.write("                <div class=\"stat-icon\">&#127968;</div>\n");
      out.write("                <div class=\"stat-value\" id=\"totalHouses\">--</div>\n");
      out.write("                <div class=\"stat-label\">我的房源数</div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"stat-card\">\n");
      out.write("                <div class=\"stat-icon\">&#9989;</div>\n");
      out.write("                <div class=\"stat-value\" id=\"freeHouses\">--</div>\n");
      out.write("                <div class=\"stat-label\">空闲房源</div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"stat-card\">\n");
      out.write("                <div class=\"stat-icon\">&#128100;</div>\n");
      out.write("                <div class=\"stat-value\" id=\"rentedHouses\">--</div>\n");
      out.write("                <div class=\"stat-label\">已租房源</div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"stat-card\">\n");
      out.write("                <div class=\"stat-icon\">&#128196;</div>\n");
      out.write("                <div class=\"stat-value\" id=\"activeContracts\">--</div>\n");
      out.write("                <div class=\"stat-label\">生效合同</div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"stat-card\">\n");
      out.write("                <div class=\"stat-icon\">&#128176;</div>\n");
      out.write("                <div class=\"stat-value\" id=\"pendingPayments\">--</div>\n");
      out.write("                <div class=\"stat-label\">待缴费用</div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/common.js\"></script>\n");
      out.write("    <script>\n");
      out.write("        /**\n");
      out.write("         * 页面初始化，加载统计数据\n");
      out.write("         */\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\n");
      out.write("            // 显示欢迎信息\n");
      out.write("            var user = JSON.parse(localStorage.getItem('user') || '{}');\n");
      out.write("            if (user.name) {\n");
      out.write("                document.getElementById('welcomeText').textContent = '欢迎回来，' + user.name + '！';\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            loadStats();\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        /**\n");
      out.write("         * 加载统计数据\n");
      out.write("         */\n");
      out.write("        function loadStats() {\n");
      out.write("            var token = localStorage.getItem('token');\n");
      out.write("            fetch('/api/owner/stats', {\n");
      out.write("                method: 'GET',\n");
      out.write("                headers: {\n");
      out.write("                    'Authorization': 'Bearer ' + token\n");
      out.write("                }\n");
      out.write("            })\n");
      out.write("            .then(function(response) {\n");
      out.write("                return response.json();\n");
      out.write("            })\n");
      out.write("            .then(function(result) {\n");
      out.write("                if (result.code === 200 && result.data) {\n");
      out.write("                    var data = result.data;\n");
      out.write("                    document.getElementById('totalHouses').textContent = data.totalHouses || 0;\n");
      out.write("                    document.getElementById('freeHouses').textContent = data.freeHouses || 0;\n");
      out.write("                    document.getElementById('rentedHouses').textContent = data.rentedHouses || 0;\n");
      out.write("                    document.getElementById('activeContracts').textContent = data.activeContracts || 0;\n");
      out.write("                    document.getElementById('pendingPayments').textContent = data.pendingPayments || 0;\n");
      out.write("                } else {\n");
      out.write("                    alert('获取统计数据失败：' + (result.message || '未知错误'));\n");
      out.write("                }\n");
      out.write("            })\n");
      out.write("            .catch(function(error) {\n");
      out.write("                console.error('加载统计数据失败：', error);\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
