/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2026-07-10 06:52:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class payment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/admin/sidebar.jsp", Long.valueOf(1783665526381L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"zh-CN\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>费用管理 - 房屋租赁系统管理端</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/style.css\">\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            display: flex;\n");
      out.write("            min-height: 100vh;\n");
      out.write("            background-color: #f0f2f5;\n");
      out.write("            font-family: \"Microsoft YaHei\", sans-serif;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .main-content {\n");
      out.write("            flex: 1;\n");
      out.write("            padding: 24px;\n");
      out.write("            margin-left: 220px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .page-header {\n");
      out.write("            margin-bottom: 24px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .page-header h1 {\n");
      out.write("            font-size: 24px;\n");
      out.write("            color: #333;\n");
      out.write("            margin: 0 0 8px 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .page-header p {\n");
      out.write("            color: #666;\n");
      out.write("            margin: 0;\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .toolbar {\n");
      out.write("            background: #fff;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            padding: 16px 20px;\n");
      out.write("            margin-bottom: 16px;\n");
      out.write("            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.06);\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 12px;\n");
      out.write("            flex-wrap: wrap;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .toolbar select {\n");
      out.write("            padding: 8px 12px;\n");
      out.write("            border: 1px solid #d9d9d9;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            font-size: 14px;\n");
      out.write("            width: 140px;\n");
      out.write("            outline: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .toolbar select:focus {\n");
      out.write("            border-color: #1890ff;\n");
      out.write("            box-shadow: 0 0 0 2px rgba(24, 144, 255, 0.2);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn {\n");
      out.write("            padding: 8px 16px;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            font-size: 14px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: all 0.2s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary {\n");
      out.write("            background: #1890ff;\n");
      out.write("            color: #fff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary:hover {\n");
      out.write("            background: #40a9ff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-success {\n");
      out.write("            background: #52c41a;\n");
      out.write("            color: #fff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-success:hover {\n");
      out.write("            background: #73d13d;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-danger {\n");
      out.write("            background: #ff4d4f;\n");
      out.write("            color: #fff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-danger:hover {\n");
      out.write("            background: #ff7875;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-small {\n");
      out.write("            padding: 4px 10px;\n");
      out.write("            font-size: 12px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .table-container {\n");
      out.write("            background: #fff;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.06);\n");
      out.write("            overflow: hidden;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        table {\n");
      out.write("            width: 100%;\n");
      out.write("            border-collapse: collapse;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        table th, table td {\n");
      out.write("            padding: 12px 16px;\n");
      out.write("            text-align: left;\n");
      out.write("            border-bottom: 1px solid #f0f0f0;\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        table th {\n");
      out.write("            background: #fafafa;\n");
      out.write("            color: #333;\n");
      out.write("            font-weight: 600;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        table tr:hover {\n");
      out.write("            background: #f5f5f5;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-paid {\n");
      out.write("            display: inline-block;\n");
      out.write("            padding: 2px 8px;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            background: #f6ffed;\n");
      out.write("            color: #52c41a;\n");
      out.write("            font-size: 12px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-unpaid {\n");
      out.write("            display: inline-block;\n");
      out.write("            padding: 2px 8px;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            background: #fff1f0;\n");
      out.write("            color: #ff4d4f;\n");
      out.write("            font-size: 12px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .pagination {\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: flex-end;\n");
      out.write("            align-items: center;\n");
      out.write("            padding: 16px 20px;\n");
      out.write("            gap: 8px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .pagination button {\n");
      out.write("            padding: 6px 12px;\n");
      out.write("            border: 1px solid #d9d9d9;\n");
      out.write("            background: #fff;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            font-size: 13px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .pagination button:hover {\n");
      out.write("            border-color: #1890ff;\n");
      out.write("            color: #1890ff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .pagination button:disabled {\n");
      out.write("            color: #d9d9d9;\n");
      out.write("            cursor: not-allowed;\n");
      out.write("            border-color: #d9d9d9;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .pagination .page-info {\n");
      out.write("            font-size: 13px;\n");
      out.write("            color: #666;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .action-btns {\n");
      out.write("            display: flex;\n");
      out.write("            gap: 6px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* 模态框样式 */\n");
      out.write("        .modal-overlay {\n");
      out.write("            display: none;\n");
      out.write("            position: fixed;\n");
      out.write("            top: 0;\n");
      out.write("            left: 0;\n");
      out.write("            width: 100%;\n");
      out.write("            height: 100%;\n");
      out.write("            background: rgba(0, 0, 0, 0.5);\n");
      out.write("            z-index: 1000;\n");
      out.write("            justify-content: center;\n");
      out.write("            align-items: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .modal-overlay.active {\n");
      out.write("            display: flex;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .modal {\n");
      out.write("            background: #fff;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            padding: 24px;\n");
      out.write("            width: 420px;\n");
      out.write("            max-width: 90%;\n");
      out.write("            box-shadow: 0 4px 24px rgba(0, 0, 0, 0.15);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .modal h3 {\n");
      out.write("            margin: 0 0 20px 0;\n");
      out.write("            font-size: 18px;\n");
      out.write("            color: #333;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group {\n");
      out.write("            margin-bottom: 16px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group label {\n");
      out.write("            display: block;\n");
      out.write("            margin-bottom: 6px;\n");
      out.write("            font-size: 14px;\n");
      out.write("            color: #333;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group input,\n");
      out.write("        .form-group select {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 8px 12px;\n");
      out.write("            border: 1px solid #d9d9d9;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            font-size: 14px;\n");
      out.write("            outline: none;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group input:focus,\n");
      out.write("        .form-group select:focus {\n");
      out.write("            border-color: #1890ff;\n");
      out.write("            box-shadow: 0 0 0 2px rgba(24, 144, 255, 0.2);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .modal-actions {\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: flex-end;\n");
      out.write("            gap: 12px;\n");
      out.write("            margin-top: 24px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-cancel {\n");
      out.write("            background: #f0f0f0;\n");
      out.write("            color: #666;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-cancel:hover {\n");
      out.write("            background: #d9d9d9;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    ");
      out.write("\n");
      out.write("<div class=\"sidebar\">\n");
      out.write("    <div class=\"sidebar-logo\">房屋租赁系统</div>\n");
      out.write("    <ul class=\"sidebar-menu\">\n");
      out.write("        <li><a href=\"dashboard.jsp\"><span class=\"icon\">&#128200;</span>系统概览</a></li>\n");
      out.write("        <li><a href=\"owner.jsp\"><span class=\"icon\">&#127968;</span>房东管理</a></li>\n");
      out.write("        <li><a href=\"tenant.jsp\"><span class=\"icon\">&#128101;</span>租户管理</a></li>\n");
      out.write("        <li><a href=\"house.jsp\"><span class=\"icon\">&#127970;</span>房源管理</a></li>\n");
      out.write("        <li><a href=\"contract.jsp\"><span class=\"icon\">&#128196;</span>合同管理</a></li>\n");
      out.write("        <li><a href=\"payment.jsp\"><span class=\"icon\">&#128176;</span>费用管理</a></li>\n");
      out.write("        <li><a href=\"review.jsp\"><span class=\"icon\">&#11088;</span>评价管理</a></li>\n");
      out.write("        <li><a href=\"javascript:void(0)\" onclick=\"logout()\"><span class=\"icon\">&#128682;</span>退出登录</a></li>\n");
      out.write("    </ul>\n");
      out.write("</div>\n");
      out.write("<script>\n");
      out.write("    function logout() {\n");
      out.write("        localStorage.removeItem('token');\n");
      out.write("        localStorage.removeItem('user');\n");
      out.write("        localStorage.removeItem('role');\n");
      out.write("        window.location.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login.jsp';\n");
      out.write("    }\n");
      out.write("    document.addEventListener('DOMContentLoaded', function() {\n");
      out.write("        var currentPage = window.location.pathname.split('/').pop();\n");
      out.write("        var items = document.querySelectorAll('.sidebar-menu li a');\n");
      out.write("        items.forEach(function(item) {\n");
      out.write("            if (item.getAttribute('href') === currentPage) {\n");
      out.write("                item.parentElement.classList.add('active');\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"main-content\">\n");
      out.write("        <div class=\"page-header\">\n");
      out.write("            <h1>费用管理</h1>\n");
      out.write("            <p>查看和管理所有费用记录</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"toolbar\">\n");
      out.write("            <select id=\"payStatusFilter\">\n");
      out.write("                <option value=\"\">全部缴费状态</option>\n");
      out.write("                <option value=\"0\">未缴</option>\n");
      out.write("                <option value=\"1\">已缴</option>\n");
      out.write("            </select>\n");
      out.write("            <select id=\"paymentTypeFilter\">\n");
      out.write("                <option value=\"\">全部费用类型</option>\n");
      out.write("                <option value=\"租金\">租金</option>\n");
      out.write("                <option value=\"押金\">押金</option>\n");
      out.write("                <option value=\"水电费\">水电费</option>\n");
      out.write("                <option value=\"物业费\">物业费</option>\n");
      out.write("            </select>\n");
      out.write("            <button class=\"btn btn-primary\" onclick=\"loadData(1)\">筛选</button>\n");
      out.write("            <button class=\"btn btn-success\" onclick=\"openAddModal()\">新增费用</button>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"table-container\">\n");
      out.write("            <table>\n");
      out.write("                <thead>\n");
      out.write("                    <tr>\n");
      out.write("                        <th>编号</th>\n");
      out.write("                        <th>合同编号</th>\n");
      out.write("                        <th>费用类型</th>\n");
      out.write("                        <th>金额</th>\n");
      out.write("                        <th>缴费状态</th>\n");
      out.write("                        <th>缴费日期</th>\n");
      out.write("                        <th>操作</th>\n");
      out.write("                    </tr>\n");
      out.write("                </thead>\n");
      out.write("                <tbody id=\"tableBody\">\n");
      out.write("                    <tr>\n");
      out.write("                        <td colspan=\"7\" style=\"text-align:center;color:#999;padding:40px;\">加载中...</td>\n");
      out.write("                    </tr>\n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("            <div class=\"pagination\" id=\"pagination\"></div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- 新增费用模态框 -->\n");
      out.write("    <div class=\"modal-overlay\" id=\"addModal\">\n");
      out.write("        <div class=\"modal\">\n");
      out.write("            <h3>新增费用</h3>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label>合同编号</label>\n");
      out.write("                <input type=\"number\" id=\"addContractId\" placeholder=\"请输入合同编号\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label>费用类型</label>\n");
      out.write("                <select id=\"addPaymentType\">\n");
      out.write("                    <option value=\"租金\">租金</option>\n");
      out.write("                    <option value=\"押金\">押金</option>\n");
      out.write("                    <option value=\"水电费\">水电费</option>\n");
      out.write("                    <option value=\"物业费\">物业费</option>\n");
      out.write("                </select>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label>金额</label>\n");
      out.write("                <input type=\"number\" id=\"addAmount\" placeholder=\"请输入金额\" step=\"0.01\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-actions\">\n");
      out.write("                <button class=\"btn btn-cancel\" onclick=\"closeAddModal()\">取消</button>\n");
      out.write("                <button class=\"btn btn-primary\" onclick=\"submitAdd()\">确认添加</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/common.js\"></script>\n");
      out.write("    <script>\n");
      out.write("        var currentPage = 1;\n");
      out.write("        var pageSize = 10;\n");
      out.write("\n");
      out.write("        /**\n");
      out.write("         * 页面初始化\n");
      out.write("         */\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\n");
      out.write("            loadData(1);\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        /**\n");
      out.write("         * 加载费用列表数据\n");
      out.write("         * @param {number} page 页码\n");
      out.write("         */\n");
      out.write("        function loadData(page) {\n");
      out.write("            currentPage = page;\n");
      out.write("            var payStatus = document.getElementById('payStatusFilter').value;\n");
      out.write("            var paymentType = document.getElementById('paymentTypeFilter').value;\n");
      out.write("            var token = localStorage.getItem('token');\n");
      out.write("\n");
      out.write("            var url = '/api/admin/payment?page=' + page + '&pageSize=' + pageSize;\n");
      out.write("            if (payStatus !== '') {\n");
      out.write("                url += '&payStatus=' + payStatus;\n");
      out.write("            }\n");
      out.write("            if (paymentType !== '') {\n");
      out.write("                url += '&paymentType=' + encodeURIComponent(paymentType);\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            fetch(url, {\n");
      out.write("                method: 'GET',\n");
      out.write("                headers: {\n");
      out.write("                    'Authorization': 'Bearer ' + token\n");
      out.write("                }\n");
      out.write("            })\n");
      out.write("            .then(function(response) {\n");
      out.write("                return response.json();\n");
      out.write("            })\n");
      out.write("            .then(function(result) {\n");
      out.write("                if (result.code === 200 && result.data) {\n");
      out.write("                    renderTable(result.data.list || []);\n");
      out.write("                    renderPagination(result.data.total || 0);\n");
      out.write("                } else {\n");
      out.write("                    alert('获取数据失败：' + (result.message || '未知错误'));\n");
      out.write("                }\n");
      out.write("            })\n");
      out.write("            .catch(function(error) {\n");
      out.write("                console.error('加载数据失败：', error);\n");
      out.write("                document.getElementById('tableBody').innerHTML =\n");
      out.write("                    '<tr><td colspan=\"7\" style=\"text-align:center;color:#ff4d4f;padding:40px;\">加载失败，请稍后重试</td></tr>';\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /**\n");
      out.write("         * 渲染表格数据\n");
      out.write("         * @param {Array} list 费用列表\n");
      out.write("         */\n");
      out.write("        function renderTable(list) {\n");
      out.write("            var tbody = document.getElementById('tableBody');\n");
      out.write("            if (!list || list.length === 0) {\n");
      out.write("                tbody.innerHTML = '<tr><td colspan=\"7\" style=\"text-align:center;color:#999;padding:40px;\">暂无数据</td></tr>';\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            var html = '';\n");
      out.write("            list.forEach(function(item) {\n");
      out.write("                var statusClass = item.payStatus === 1 ? 'status-paid' : 'status-unpaid';\n");
      out.write("                var statusText = item.payStatus === 1 ? '已缴' : '未缴';\n");
      out.write("\n");
      out.write("                html += '<tr>';\n");
      out.write("                html += '<td>' + (item.id || '') + '</td>';\n");
      out.write("                html += '<td>' + (item.contractId || '') + '</td>';\n");
      out.write("                html += '<td>' + (item.paymentType || '') + '</td>';\n");
      out.write("                html += '<td>' + (item.amount ? '¥' + item.amount : '') + '</td>';\n");
      out.write("                html += '<td><span class=\"' + statusClass + '\">' + statusText + '</span></td>';\n");
      out.write("                html += '<td>' + (item.payDate || '--') + '</td>';\n");
      out.write("                html += '<td class=\"action-btns\">';\n");
      out.write("                if (item.payStatus === 0) {\n");
      out.write("                    html += '<button class=\"btn btn-success btn-small\" onclick=\"markAsPaid(' + item.id + ')\">标记已缴</button>';\n");
      out.write("                }\n");
      out.write("                html += '</td>';\n");
      out.write("                html += '</tr>';\n");
      out.write("            });\n");
      out.write("            tbody.innerHTML = html;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /**\n");
      out.write("         * 渲染分页控件\n");
      out.write("         * @param {number} total 总记录数\n");
      out.write("         */\n");
      out.write("        function renderPagination(total) {\n");
      out.write("            var container = document.getElementById('pagination');\n");
      out.write("            var totalPages = Math.ceil(total / pageSize);\n");
      out.write("\n");
      out.write("            if (totalPages <= 1) {\n");
      out.write("                container.innerHTML = '<span class=\"page-info\">共 ' + total + ' 条记录</span>';\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            var html = '';\n");
      out.write("            html += '<button ' + (currentPage <= 1 ? 'disabled' : '') + ' onclick=\"loadData(' + (currentPage - 1) + ')\">上一页</button>';\n");
      out.write("            html += '<span class=\"page-info\">第 ' + currentPage + ' / ' + totalPages + ' 页，共 ' + total + ' 条</span>';\n");
      out.write("            html += '<button ' + (currentPage >= totalPages ? 'disabled' : '') + ' onclick=\"loadData(' + (currentPage + 1) + ')\">下一页</button>';\n");
      out.write("            container.innerHTML = html;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /**\n");
      out.write("         * 标记费用为已缴\n");
      out.write("         * @param {number} id 费用ID\n");
      out.write("         */\n");
      out.write("        function markAsPaid(id) {\n");
      out.write("            if (!confirm('确定要将该费用标记为已缴吗？')) {\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            var token = localStorage.getItem('token');\n");
      out.write("            fetch('/api/admin/payment/' + id + '/pay', {\n");
      out.write("                method: 'PUT',\n");
      out.write("                headers: {\n");
      out.write("                    'Authorization': 'Bearer ' + token\n");
      out.write("                }\n");
      out.write("            })\n");
      out.write("            .then(function(response) {\n");
      out.write("                return response.json();\n");
      out.write("            })\n");
      out.write("            .then(function(result) {\n");
      out.write("                if (result.code === 200) {\n");
      out.write("                    loadData(currentPage);\n");
      out.write("                } else {\n");
      out.write("                    alert('操作失败：' + (result.message || '未知错误'));\n");
      out.write("                }\n");
      out.write("            })\n");
      out.write("            .catch(function(error) {\n");
      out.write("                console.error('操作失败：', error);\n");
      out.write("                alert('操作失败，请稍后重试');\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /**\n");
      out.write("         * 打开新增费用模态框\n");
      out.write("         */\n");
      out.write("        function openAddModal() {\n");
      out.write("            document.getElementById('addContractId').value = '';\n");
      out.write("            document.getElementById('addPaymentType').value = '租金';\n");
      out.write("            document.getElementById('addAmount').value = '';\n");
      out.write("            document.getElementById('addModal').classList.add('active');\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /**\n");
      out.write("         * 关闭新增费用模态框\n");
      out.write("         */\n");
      out.write("        function closeAddModal() {\n");
      out.write("            document.getElementById('addModal').classList.remove('active');\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /**\n");
      out.write("         * 提交新增费用\n");
      out.write("         */\n");
      out.write("        function submitAdd() {\n");
      out.write("            var contractId = document.getElementById('addContractId').value.trim();\n");
      out.write("            var paymentType = document.getElementById('addPaymentType').value;\n");
      out.write("            var amount = document.getElementById('addAmount').value.trim();\n");
      out.write("\n");
      out.write("            if (!contractId) {\n");
      out.write("                alert('请输入合同编号');\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("            if (!amount || parseFloat(amount) <= 0) {\n");
      out.write("                alert('请输入有效的金额');\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            var token = localStorage.getItem('token');\n");
      out.write("            fetch('/api/admin/payment', {\n");
      out.write("                method: 'POST',\n");
      out.write("                headers: {\n");
      out.write("                    'Authorization': 'Bearer ' + token,\n");
      out.write("                    'Content-Type': 'application/json'\n");
      out.write("                },\n");
      out.write("                body: JSON.stringify({\n");
      out.write("                    contractId: parseInt(contractId),\n");
      out.write("                    paymentType: paymentType,\n");
      out.write("                    amount: parseFloat(amount)\n");
      out.write("                })\n");
      out.write("            })\n");
      out.write("            .then(function(response) {\n");
      out.write("                return response.json();\n");
      out.write("            })\n");
      out.write("            .then(function(result) {\n");
      out.write("                if (result.code === 200) {\n");
      out.write("                    closeAddModal();\n");
      out.write("                    loadData(currentPage);\n");
      out.write("                } else {\n");
      out.write("                    alert('添加失败：' + (result.message || '未知错误'));\n");
      out.write("                }\n");
      out.write("            })\n");
      out.write("            .catch(function(error) {\n");
      out.write("                console.error('添加失败：', error);\n");
      out.write("                alert('添加失败，请稍后重试');\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
