/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2026-07-10 02:55:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"zh-CN\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>登录 - 房屋租赁管理系统</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/style.css\">\n");
      out.write("    <style>\n");
      out.write("        /* 登录页面样式 */\n");
      out.write("        body {\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            min-height: 100vh;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n");
      out.write("            font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .login-card {\n");
      out.write("            background: #fff;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);\n");
      out.write("            padding: 40px;\n");
      out.write("            width: 100%;\n");
      out.write("            max-width: 420px;\n");
      out.write("            margin: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .login-card h1 {\n");
      out.write("            text-align: center;\n");
      out.write("            color: #333;\n");
      out.write("            font-size: 24px;\n");
      out.write("            margin: 0 0 30px 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* 角色选择标签 */\n");
      out.write("        .role-tabs {\n");
      out.write("            display: flex;\n");
      out.write("            border-bottom: 2px solid #e9ecef;\n");
      out.write("            margin-bottom: 25px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .role-tab {\n");
      out.write("            flex: 1;\n");
      out.write("            text-align: center;\n");
      out.write("            padding: 12px 0;\n");
      out.write("            cursor: pointer;\n");
      out.write("            color: #666;\n");
      out.write("            font-size: 14px;\n");
      out.write("            border-bottom: 2px solid transparent;\n");
      out.write("            margin-bottom: -2px;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .role-tab:hover {\n");
      out.write("            color: #667eea;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .role-tab.active {\n");
      out.write("            color: #667eea;\n");
      out.write("            border-bottom-color: #667eea;\n");
      out.write("            font-weight: 500;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* 表单样式 */\n");
      out.write("        .form-group {\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group label {\n");
      out.write("            display: block;\n");
      out.write("            margin-bottom: 8px;\n");
      out.write("            color: #555;\n");
      out.write("            font-size: 14px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group input {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 12px 15px;\n");
      out.write("            border: 1px solid #ddd;\n");
      out.write("            border-radius: 6px;\n");
      out.write("            font-size: 14px;\n");
      out.write("            transition: border-color 0.3s ease;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group input:focus {\n");
      out.write("            outline: none;\n");
      out.write("            border-color: #667eea;\n");
      out.write("            box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.1);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* 登录按钮 */\n");
      out.write("        .login-btn {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 14px;\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n");
      out.write("            color: #fff;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 6px;\n");
      out.write("            font-size: 16px;\n");
      out.write("            font-weight: 500;\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: transform 0.2s ease, box-shadow 0.2s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .login-btn:hover {\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("            box-shadow: 0 5px 20px rgba(102, 126, 234, 0.4);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .login-btn:active {\n");
      out.write("            transform: translateY(0);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* 注册链接 */\n");
      out.write("        .register-link {\n");
      out.write("            text-align: center;\n");
      out.write("            margin-top: 20px;\n");
      out.write("            font-size: 14px;\n");
      out.write("            color: #666;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .register-link a {\n");
      out.write("            color: #667eea;\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-weight: 500;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .register-link a:hover {\n");
      out.write("            text-decoration: underline;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* 隐藏元素 */\n");
      out.write("        .hidden {\n");
      out.write("            display: none;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"login-card\">\n");
      out.write("        <h1>房屋租赁管理系统</h1>\n");
      out.write("\n");
      out.write("        <!-- 角色选择标签 -->\n");
      out.write("        <div class=\"role-tabs\">\n");
      out.write("            <div class=\"role-tab active\" data-role=\"owner\" onclick=\"switchRole('owner')\">房东登录</div>\n");
      out.write("            <div class=\"role-tab\" data-role=\"tenant\" onclick=\"switchRole('tenant')\">租户登录</div>\n");
      out.write("            <div class=\"role-tab\" data-role=\"admin\" onclick=\"switchRole('admin')\">管理员登录</div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- 登录表单 -->\n");
      out.write("        <form id=\"loginForm\" onsubmit=\"handleLogin(event)\">\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label id=\"accountLabel\" for=\"account\">手机号</label>\n");
      out.write("                <input type=\"text\" id=\"account\" name=\"account\" placeholder=\"请输入手机号\" required>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"password\">密码</label>\n");
      out.write("                <input type=\"password\" id=\"password\" name=\"password\" placeholder=\"请输入密码\" required>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <button type=\"submit\" class=\"login-btn\">登 录</button>\n");
      out.write("        </form>\n");
      out.write("\n");
      out.write("        <!-- 注册链接（仅房东和租户显示） -->\n");
      out.write("        <div class=\"register-link\" id=\"registerLink\">\n");
      out.write("            还没有账号？<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register.jsp\">立即注册</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/common.js\"></script>\n");
      out.write("    <script>\n");
      out.write("        // 当前选中的角色\n");
      out.write("        let currentRole = 'owner';\n");
      out.write("\n");
      out.write("        // 页面加载时设置默认值\n");
      out.write("        window.onload = function() {\n");
      out.write("            document.getElementById('account').value = '13800000001';\n");
      out.write("            document.getElementById('password').value = '123456';\n");
      out.write("        };\n");
      out.write("\n");
      out.write("        /**\n");
      out.write("         * 切换角色\n");
      out.write("         * @param {string} role - 角色类型: owner/tenant/admin\n");
      out.write("         */\n");
      out.write("        function switchRole(role) {\n");
      out.write("            currentRole = role;\n");
      out.write("\n");
      out.write("            // 更新标签样式\n");
      out.write("            document.querySelectorAll('.role-tab').forEach(tab => {\n");
      out.write("                tab.classList.remove('active');\n");
      out.write("                if (tab.dataset.role === role) {\n");
      out.write("                    tab.classList.add('active');\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            // 获取输入框元素\n");
      out.write("            const accountLabel = document.getElementById('accountLabel');\n");
      out.write("            const accountInput = document.getElementById('account');\n");
      out.write("            const passwordInput = document.getElementById('password');\n");
      out.write("            const registerLink = document.getElementById('registerLink');\n");
      out.write("\n");
      out.write("            // 更新输入框标签和默认值\n");
      out.write("            if (role === 'admin') {\n");
      out.write("                accountLabel.textContent = '用户名';\n");
      out.write("                accountInput.placeholder = '请输入用户名';\n");
      out.write("                accountInput.value = 'admin';\n");
      out.write("                passwordInput.value = '123456';\n");
      out.write("                registerLink.classList.add('hidden');\n");
      out.write("            } else if (role === 'tenant') {\n");
      out.write("                accountLabel.textContent = '手机号';\n");
      out.write("                accountInput.placeholder = '请输入手机号';\n");
      out.write("                accountInput.value = '13900000001';\n");
      out.write("                passwordInput.value = '123456';\n");
      out.write("                registerLink.classList.remove('hidden');\n");
      out.write("            } else {\n");
      out.write("                accountLabel.textContent = '手机号';\n");
      out.write("                accountInput.placeholder = '请输入手机号';\n");
      out.write("                accountInput.value = '13800000001';\n");
      out.write("                passwordInput.value = '123456';\n");
      out.write("                registerLink.classList.remove('hidden');\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /**\n");
      out.write("         * 处理登录\n");
      out.write("         * @param {Event} e - 表单提交事件\n");
      out.write("         */\n");
      out.write("        async function handleLogin(e) {\n");
      out.write("            e.preventDefault();\n");
      out.write("\n");
      out.write("            const account = document.getElementById('account').value.trim();\n");
      out.write("            const password = document.getElementById('password').value.trim();\n");
      out.write("\n");
      out.write("            // 表单验证\n");
      out.write("            if (!account) {\n");
      out.write("                alert(currentRole === 'admin' ? '请输入用户名' : '请输入手机号');\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("            if (!password) {\n");
      out.write("                alert('请输入密码');\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            // 构建请求参数\n");
      out.write("            let apiUrl = '';\n");
      out.write("            let requestBody = {};\n");
      out.write("\n");
      out.write("            if (currentRole === 'owner') {\n");
      out.write("                apiUrl = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/api/owner/auth?action=login';\n");
      out.write("                requestBody = { phone: account, password: password };\n");
      out.write("            } else if (currentRole === 'tenant') {\n");
      out.write("                apiUrl = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/api/tenant/auth?action=login';\n");
      out.write("                requestBody = { phone: account, password: password };\n");
      out.write("            } else if (currentRole === 'admin') {\n");
      out.write("                apiUrl = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/api/admin/auth?action=login';\n");
      out.write("                requestBody = { username: account, password: password };\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            try {\n");
      out.write("                // 禁用登录按钮\n");
      out.write("                const loginBtn = document.querySelector('.login-btn');\n");
      out.write("                loginBtn.disabled = true;\n");
      out.write("                loginBtn.textContent = '登录中...';\n");
      out.write("\n");
      out.write("                const response = await fetch(apiUrl, {\n");
      out.write("                    method: 'POST',\n");
      out.write("                    headers: {\n");
      out.write("                        'Content-Type': 'application/json'\n");
      out.write("                    },\n");
      out.write("                    body: JSON.stringify(requestBody)\n");
      out.write("                });\n");
      out.write("\n");
      out.write("                const result = await response.json();\n");
      out.write("\n");
      out.write("                if (result.code === 200) {\n");
      out.write("                    // 保存token和用户信息到localStorage\n");
      out.write("                    localStorage.setItem('token', result.data.token);\n");
      out.write("                    localStorage.setItem('userInfo', JSON.stringify(result.data.userInfo || result.data));\n");
      out.write("                    localStorage.setItem('role', currentRole);\n");
      out.write("\n");
      out.write("                    // 根据角色跳转到对应的dashboard\n");
      out.write("                    let redirectUrl = '';\n");
      out.write("                    if (currentRole === 'owner') {\n");
      out.write("                        redirectUrl = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/owner/dashboard.jsp';\n");
      out.write("                    } else if (currentRole === 'tenant') {\n");
      out.write("                        redirectUrl = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/tenant/dashboard.jsp';\n");
      out.write("                    } else if (currentRole === 'admin') {\n");
      out.write("                        redirectUrl = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/dashboard.jsp';\n");
      out.write("                    }\n");
      out.write("\n");
      out.write("                    window.location.href = redirectUrl;\n");
      out.write("                } else {\n");
      out.write("                    // 显示错误信息\n");
      out.write("                    alert(result.message || '登录失败，请重试');\n");
      out.write("                    loginBtn.disabled = false;\n");
      out.write("                    loginBtn.textContent = '登 录';\n");
      out.write("                }\n");
      out.write("            } catch (error) {\n");
      out.write("                console.error('登录请求失败:', error);\n");
      out.write("                alert('网络错误，请稍后重试');\n");
      out.write("                const loginBtn = document.querySelector('.login-btn');\n");
      out.write("                loginBtn.disabled = false;\n");
      out.write("                loginBtn.textContent = '登 录';\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
