/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2026-07-10 06:45:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tenant;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/tenant/sidebar.jsp", Long.valueOf(1783665519481L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"zh-CN\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>首页概览 - 租户端</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"container\">\n");
      out.write("        ");
      out.write("\n");
      out.write("<div class=\"sidebar\">\n");
      out.write("    <div class=\"sidebar-logo\">房屋租赁系统</div>\n");
      out.write("    <ul class=\"sidebar-menu\">\n");
      out.write("        <li><a href=\"dashboard.jsp\"><span class=\"icon\">&#127968;</span>首页</a></li>\n");
      out.write("        <li><a href=\"house.jsp\"><span class=\"icon\">&#128269;</span>浏览房源</a></li>\n");
      out.write("        <li><a href=\"contract.jsp\"><span class=\"icon\">&#128196;</span>我的合同</a></li>\n");
      out.write("        <li><a href=\"payment.jsp\"><span class=\"icon\">&#128176;</span>我的费用</a></li>\n");
      out.write("        <li><a href=\"review.jsp\"><span class=\"icon\">&#11088;</span>我的评价</a></li>\n");
      out.write("        <li><a href=\"profile.jsp\"><span class=\"icon\">&#128100;</span>个人信息</a></li>\n");
      out.write("        <li><a href=\"javascript:void(0)\" onclick=\"logout()\"><span class=\"icon\">&#128682;</span>退出登录</a></li>\n");
      out.write("    </ul>\n");
      out.write("</div>\n");
      out.write("<script>\n");
      out.write("    function logout() {\n");
      out.write("        localStorage.removeItem('token');\n");
      out.write("        localStorage.removeItem('user');\n");
      out.write("        localStorage.removeItem('role');\n");
      out.write("        window.location.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login.jsp';\n");
      out.write("    }\n");
      out.write("    document.addEventListener('DOMContentLoaded', function() {\n");
      out.write("        var currentPage = window.location.pathname.split('/').pop();\n");
      out.write("        var items = document.querySelectorAll('.sidebar-menu li a');\n");
      out.write("        items.forEach(function(item) {\n");
      out.write("            if (item.getAttribute('href') === currentPage) {\n");
      out.write("                item.parentElement.classList.add('active');\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("        <main class=\"main-content\">\n");
      out.write("            <h2>首页概览</h2>\n");
      out.write("            <div class=\"stats-cards\" id=\"statsCards\">\n");
      out.write("                <div class=\"stat-card\">\n");
      out.write("                    <div class=\"stat-label\">生效合同数</div>\n");
      out.write("                    <div class=\"stat-value\" id=\"activeContracts\">--</div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"stat-card\">\n");
      out.write("                    <div class=\"stat-label\">待缴费用</div>\n");
      out.write("                    <div class=\"stat-value\" id=\"pendingPayments\">--</div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"stat-card\">\n");
      out.write("                    <div class=\"stat-label\">已缴总额</div>\n");
      out.write("                    <div class=\"stat-value\" id=\"totalPaid\">--</div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </main>\n");
      out.write("    </div>\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/common.js\"></script>\n");
      out.write("    <script>\n");
      out.write("        // 页面加载时获取统计数据\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\n");
      out.write("            loadStats();\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        function loadStats() {\n");
      out.write("            var token = localStorage.getItem('token');\n");
      out.write("            fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/api/tenant/stats', {\n");
      out.write("                method: 'GET',\n");
      out.write("                headers: {\n");
      out.write("                    'Authorization': 'Bearer ' + token\n");
      out.write("                }\n");
      out.write("            })\n");
      out.write("            .then(function(response) { return response.json(); })\n");
      out.write("            .then(function(result) {\n");
      out.write("                if (result.code === 200) {\n");
      out.write("                    var data = result.data;\n");
      out.write("                    document.getElementById('activeContracts').textContent = data.activeContracts || 0;\n");
      out.write("                    document.getElementById('pendingPayments').textContent = data.pendingPayments || 0;\n");
      out.write("                    document.getElementById('totalPaid').textContent = '¥' + (data.totalPaid || 0).toFixed(2);\n");
      out.write("                } else {\n");
      out.write("                    alert(result.message || '获取统计数据失败');\n");
      out.write("                }\n");
      out.write("            })\n");
      out.write("            .catch(function(error) {\n");
      out.write("                console.error('加载统计数据失败:', error);\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function logout() {\n");
      out.write("            localStorage.removeItem('token');\n");
      out.write("            window.location.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login.jsp';\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
